spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
