version: "3.9"

networks:
  basic:
    name: "basic"

services:
  dm:
    image: dm8_single:dm8_20230808_rev197096_x86_rh6_64
    networks:
      - basic
    restart: always
    container_name: dameng
    privileged: true
    environment:
      - PAGE_SIZE=16
      - LD_LIBRARY_PATH=/opt/dmdbms/bin
      - EXTENT_SIZE=32
      - BLANK_PAD_MODE=1
      - LOG_SIZE=1024
      - UNICODE_FLAG=1
      - LENGTH_IN_CHAR=1
      - INSTANCE_NAME=dm8
    ports:
      - '5236:5236'
    volumes:
      - ./compose/dm8/data:/opt/dmdbms/data
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    command: mongod
    networks:
      - basic
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: basic
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      wiredTigerCacheSizeGB: 2
    volumes:
      - ./compose/mongo/data:/data/db
      - ./compose/mongo/logs:/var/log/mongodb
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./compose/mongo/init.d:/docker-entrypoint-initdb.d
      - /etc/timezone:/etc/timezone:ro
  redis:
    restart: always
    networks:
      - basic
    #   image: redis:latest
    image: redis:7.2.0-alpine3.18
    container_name: redis
    volumes:
      - ./compose/redis/datadir:/data
      - ./compose/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./compose/redis/logs:/logs
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
  mysql:
    restart: always
    image: mysql:8.0.31-debian
    #   image: mysql:5.7.18
    container_name: mysql
    networks:
      - basic
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./compose/mysql/mydir:/mydir
      - ./compose/mysql/datadir:/var/lib/mysql
      - ./compose/mysql/conf/my.cnf:/etc/my.cnf
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./compose/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=basic
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    command: [ "--lower_case_table_names=1" ]