# https://gitee.com/baomidou/mybatis-plus-samples/tree/master
server:
  port: 8089
  servlet:
    context-path: /mp

spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/basic
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.58.130:3306/basic
    password: 123456
    username: root
  sql:
    init:
      schema-locations: classpath:db/basic.sql
      data-locations: classpath:db/basic-data.sql
      mode: always


mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml

logging:
  level:
    com.github.jianlu8023.example: debug
  config: classpath:logback-dev.xml
  file:
    path: ./logs
