// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package com.github.jianlu8023.javastudy.rpc.grpc.proto.ping;

public final class PingProto {
  private PingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ping_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ping_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ping_PongResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ping_PongResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nping.proto\022\004ping\"Q\n\013PingRequest\022\017\n\007fro" +
      "mUid\030\001 \001(\t\022\r\n\005toUid\030\002 \001(\t\022\017\n\007message\030\003 \001" +
      "(\t\022\021\n\texception\030\004 \001(\t\"R\n\014PongResponse\022\017\n" +
      "\007fromUid\030\001 \001(\t\022\r\n\005toUid\030\002 \001(\t\022\017\n\007message" +
      "\030\003 \001(\t\022\021\n\texception\030\004 \001(\t2>\n\013PingService" +
      "\022/\n\004ping\022\021.ping.PingRequest\032\022.ping.PongR" +
      "esponse\"\000BK\n3com.github.jianlu8023.javas" +
      "tudy.rpc.grpc.proto.pingB\tPingProtoP\001\210\001\001" +
      "\240\001\001\330\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ping_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ping_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ping_PingRequest_descriptor,
        new java.lang.String[] { "FromUid", "ToUid", "Message", "Exception", });
    internal_static_ping_PongResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ping_PongResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ping_PongResponse_descriptor,
        new java.lang.String[] { "FromUid", "ToUid", "Message", "Exception", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
