// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package com.github.jianlu8023.javastudy.rpc.grpc.proto.ping;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ping.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUid = 1;</code>
   */
  java.lang.String getFromUid();
  /**
   * <code>string fromUid = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromUidBytes();

  /**
   * <code>string toUid = 2;</code>
   */
  java.lang.String getToUid();
  /**
   * <code>string toUid = 2;</code>
   */
  com.google.protobuf.ByteString
      getToUidBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string exception = 4;</code>
   */
  java.lang.String getException();
  /**
   * <code>string exception = 4;</code>
   */
  com.google.protobuf.ByteString
      getExceptionBytes();
}
