// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package com.github.jianlu8023.javastudy.rpc.grpc.proto.ping;

/**
 * Protobuf type {@code ping.PingRequest}
 */
public  final class PingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ping.PingRequest)
    PingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PingRequest.newBuilder() to construct.
  private PingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PingRequest() {
    fromUid_ = "";
    toUid_ = "";
    message_ = "";
    exception_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fromUid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            toUid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            exception_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingProto.internal_static_ping_PingRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingProto.internal_static_ping_PingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.class, com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.Builder.class);
  }

  public static final int FROMUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object fromUid_;
  /**
   * <code>string fromUid = 1;</code>
   */
  public java.lang.String getFromUid() {
    java.lang.Object ref = fromUid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromUid_ = s;
      return s;
    }
  }
  /**
   * <code>string fromUid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFromUidBytes() {
    java.lang.Object ref = fromUid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object toUid_;
  /**
   * <code>string toUid = 2;</code>
   */
  public java.lang.String getToUid() {
    java.lang.Object ref = toUid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toUid_ = s;
      return s;
    }
  }
  /**
   * <code>string toUid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getToUidBytes() {
    java.lang.Object ref = toUid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCEPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object exception_;
  /**
   * <code>string exception = 4;</code>
   */
  public java.lang.String getException() {
    java.lang.Object ref = exception_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exception_ = s;
      return s;
    }
  }
  /**
   * <code>string exception = 4;</code>
   */
  public com.google.protobuf.ByteString
      getExceptionBytes() {
    java.lang.Object ref = exception_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exception_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFromUidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromUid_);
    }
    if (!getToUidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toUid_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    if (!getExceptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, exception_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFromUidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromUid_);
    }
    if (!getToUidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toUid_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    if (!getExceptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, exception_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest)) {
      return super.equals(obj);
    }
    com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest other = (com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest) obj;

    boolean result = true;
    result = result && getFromUid()
        .equals(other.getFromUid());
    result = result && getToUid()
        .equals(other.getToUid());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getException()
        .equals(other.getException());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROMUID_FIELD_NUMBER;
    hash = (53 * hash) + getFromUid().hashCode();
    hash = (37 * hash) + TOUID_FIELD_NUMBER;
    hash = (53 * hash) + getToUid().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
    hash = (53 * hash) + getException().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ping.PingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ping.PingRequest)
      com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingProto.internal_static_ping_PingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingProto.internal_static_ping_PingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.class, com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.Builder.class);
    }

    // Construct using com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      fromUid_ = "";

      toUid_ = "";

      message_ = "";

      exception_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingProto.internal_static_ping_PingRequest_descriptor;
    }

    public com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest getDefaultInstanceForType() {
      return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.getDefaultInstance();
    }

    public com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest build() {
      com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest buildPartial() {
      com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest result = new com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest(this);
      result.fromUid_ = fromUid_;
      result.toUid_ = toUid_;
      result.message_ = message_;
      result.exception_ = exception_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest) {
        return mergeFrom((com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest other) {
      if (other == com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.getDefaultInstance()) return this;
      if (!other.getFromUid().isEmpty()) {
        fromUid_ = other.fromUid_;
        onChanged();
      }
      if (!other.getToUid().isEmpty()) {
        toUid_ = other.toUid_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getException().isEmpty()) {
        exception_ = other.exception_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fromUid_ = "";
    /**
     * <code>string fromUid = 1;</code>
     */
    public java.lang.String getFromUid() {
      java.lang.Object ref = fromUid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fromUid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromUidBytes() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fromUid = 1;</code>
     */
    public Builder setFromUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromUid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fromUid = 1;</code>
     */
    public Builder clearFromUid() {
      
      fromUid_ = getDefaultInstance().getFromUid();
      onChanged();
      return this;
    }
    /**
     * <code>string fromUid = 1;</code>
     */
    public Builder setFromUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromUid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toUid_ = "";
    /**
     * <code>string toUid = 2;</code>
     */
    public java.lang.String getToUid() {
      java.lang.Object ref = toUid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string toUid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToUidBytes() {
      java.lang.Object ref = toUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string toUid = 2;</code>
     */
    public Builder setToUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toUid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string toUid = 2;</code>
     */
    public Builder clearToUid() {
      
      toUid_ = getDefaultInstance().getToUid();
      onChanged();
      return this;
    }
    /**
     * <code>string toUid = 2;</code>
     */
    public Builder setToUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toUid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object exception_ = "";
    /**
     * <code>string exception = 4;</code>
     */
    public java.lang.String getException() {
      java.lang.Object ref = exception_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exception_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exception = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exception = 4;</code>
     */
    public Builder setException(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exception_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exception = 4;</code>
     */
    public Builder clearException() {
      
      exception_ = getDefaultInstance().getException();
      onChanged();
      return this;
    }
    /**
     * <code>string exception = 4;</code>
     */
    public Builder setExceptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exception_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ping.PingRequest)
  }

  // @@protoc_insertion_point(class_scope:ping.PingRequest)
  private static final com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest();
  }

  public static com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PingRequest>
      PARSER = new com.google.protobuf.AbstractParser<PingRequest>() {
    public PingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PingRequest> getParserForType() {
    return PARSER;
  }

  public com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

