// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package com.github.jianlu8023.javastudy.rpc.grpc.proto.ping;

/**
 * Protobuf service {@code ping.PingService}
 */
public  abstract class PingService
    implements com.google.protobuf.Service {
  protected PingService() {}

  public interface Interface {
    /**
     * <code>rpc ping(.ping.PingRequest) returns (.ping.PongResponse);</code>
     */
    public abstract void ping(
        com.google.protobuf.RpcController controller,
        com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest request,
        com.google.protobuf.RpcCallback<com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new PingService() {
      @java.lang.Override
      public  void ping(
          com.google.protobuf.RpcController controller,
          com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest request,
          com.google.protobuf.RpcCallback<com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse> done) {
        impl.ping(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.ping(controller, (com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc ping(.ping.PingRequest) returns (.ping.PongResponse);</code>
   */
  public abstract void ping(
      com.google.protobuf.RpcController controller,
      com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest request,
      com.google.protobuf.RpcCallback<com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.ping(controller, (com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest)request,
          com.google.protobuf.RpcUtil.<com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void ping(
        com.google.protobuf.RpcController controller,
        com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest request,
        com.google.protobuf.RpcCallback<com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse.class,
          com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse ping(
        com.google.protobuf.RpcController controller,
        com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse ping(
        com.google.protobuf.RpcController controller,
        com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PingRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.github.jianlu8023.javastudy.rpc.grpc.proto.ping.PongResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:ping.PingService)
}

