// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.github.jianlu8023.javastudy.rpc.grpc.proto.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromUid = 1;</code>
   */
  java.lang.String getFromUid();
  /**
   * <code>string fromUid = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromUidBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
