// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.github.jianlu8023.javastudy.rpc.grpc.proto.hello;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\005hello\"0\n\014HelloRequest\022\017\n\007" +
      "fromUid\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"@\n\rHelloR" +
      "esponse\022\017\n\007fromUid\030\001 \001(\t\022\r\n\005toUid\030\002 \001(\t\022" +
      "\017\n\007message\030\003 \001(\t2G\n\014HelloService\0227\n\010sayH" +
      "ello\022\023.hello.HelloRequest\032\024.hello.HelloR" +
      "esponse\"\000BM\n4com.github.jianlu8023.javas" +
      "tudy.rpc.grpc.proto.helloB\nHelloProtoP\001\210" +
      "\001\001\240\001\001\330\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_HelloRequest_descriptor,
        new java.lang.String[] { "FromUid", "Message", });
    internal_static_hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_HelloResponse_descriptor,
        new java.lang.String[] { "FromUid", "ToUid", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
